#original ----------------------------------------------------
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 2.0
#   #always_send_full_costmap: false #default is false
#   rolling_window: false
#   resolution: 0.05 
#   width: 30 
#   height: 30 
#   #width: 50 
#   #height: 50 
#   origin_x: -15 
#   origin_y: -15 

#example1 ----------------------------------------------------
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 7.0 
#   publish_frequency: 3.5
#   #always_send_full_costmap: false #default is false
#   rolling_window: false
#   resolution: 0.05  
#   width: 15 
#   height: 15 
#   origin_x: -15 
#   origin_y: -15 

#example2 ----------------------------------------------------
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 7.0 
#   publish_frequency: 3.5
#   #always_send_full_costmap: false #default is false
#   rolling_window: false
#   resolution: 0.05  
#   width: 15 
#   height: 15 
#   origin_x: -15 
#   origin_y: -15 

#example3 ----------------------------------------------------
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 2.0
#   #always_send_full_costmap: false #default is false
#   rolling_window: false
#   resolution: 0.05 
#   width: 15 
#   height: 15 
#   origin_x: -15 
#   origin_y: -15 

#example4 ----------------------------------------------------
# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 10.0
#   #always_send_full_costmap: false #default is false
#   rolling_window: false
#   resolution: 0.05 
#   width: 10 
#   height: 10 
#   origin_x: -10 
#   origin_y: -10 

  #example5 ----------------------------------------------------
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 
  publish_frequency: 10.0
  #always_send_full_costmap: false #default is false
  rolling_window: false
  resolution: 0.05 
  width: 10 
  height: 10 
  origin_x: -10 
  origin_y: -10 