#original -------------------------------------------------------
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 10.0 
#   static_map: false
#   rolling_window: true
#   width: 7.0 
#   height: 7.0 
#   resolution: 0.03 

#example1 -------------------------------------------------------
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 15.0 
#   publish_frequency: 30.0 
#   static_map: false
#   rolling_window: true
#   width: 15.0 
#   height: 15.0 
#   resolution: 0.05 

# example2 -------------------------------------------------------
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 15.0 
#   publish_frequency: 30.0 
#   static_map: false
#   rolling_window: true
#   width: 15.0 
#   height: 15.0 
#   resolution: 0.05 

# example3 -------------------------------------------------------
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 10.0 
#   static_map: false
#   rolling_window: true
#   width: 15.0 
#   height: 15.0 
#   resolution: 0.03

# example4 -------------------------------------------------------
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0 
#   publish_frequency: 10.0 
#   static_map: false
#   rolling_window: true
#   width: 10.0 
#   height: 10.0 
#   resolution: 0.03

# example5 -------------------------------------------------------
local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 
  publish_frequency: 10.0 
  static_map: false
  rolling_window: true
  width: 10.0 
  height: 10.0 
  resolution: 0.03

